pipeline {
    agent { label "worker-nod"}
    environment {
        DOCKER_IMAGE = "akifmhd/python-application:v1"
        APP_NAME = "akifmhd/python-web"
        TAG_VERSION = "v1.0.0"
    }

    stages {
        stage('Docker login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'akifmhd', passwordVariable: 'password', usernameVariable: 'username')]) {
                    echo "logging into dockerhub"
                    sh "docker login -u ${username} -p ${password}"
                    echo "Docker login successful"
                }
            }
        }
            stage('Docker Image pull') {
            steps {
                    echo "Pulling docker image"
                    sh "docker pull ${DOCKER_IMAGE}"
                    echo "Docker pull successful"
               }
            }
            stage('Docker tag') {
            steps {
                    echo "Tagging the image"
                    sh "docker tag ${DOCKER_IMAGE} ${APP_NAME}:${TAG_VERSION}"
                    echo "Image tagged successfully "
                }
            }
            stage('Docker push') {
                steps {
                    echo "Docker image pushing"
                    sh "docker push ${APP_NAME}:${TAG_VERSION}"
                    echo "Docker push is successful"
                }
            }
    }
}