pipeline {
    agent { label "worker-nod"}

    stages {
        stage('Docker cred and val') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'akifmhd', passwordVariable: 'password', usernameVariable: 'username')]){
                    echo "Hello World"
                    echo "Docker username: ${username}"
                }
            }
        }
    }
}